README.md
sharing -> sharding，missing “d”
=> Spelling mistakes

src/executor/aggregate_executor_test.go
the result is not the real sql result
=> test: fix the incorrect id

src/planner/aggregate_plan.go, src/planner/aggregate_plan_test.go
the issue:
mysql> select SUM(j) from a;
ERROR 1105 (HY000): unsupported: function:SUM
=> planner: bugfix the Aggregate func in uppercase

src/monitor/monitor.go
```
[prometheus metrics]:	http://{0.0.0.0}:13380/metrics
->
[prometheus metrics]:	http://0.0.0.0:13380/metrics
```
=> monitor: change the format of the monitor info convenient to copy

src/ctl/admin.go
show the info about pprof: http://0.0.0.0:6060/debug/pprof/
=> ctl: show the info about pprof

src/executor/aggregate_executor.go
The code will remove soon, `group by` will replace by `group by order by`.
=> executor: order by add table name validate #215

makefile, src/executor/aggregate_executor.go, src/planner/aggregate_plan.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/sqltypes/aggregation.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/sqltypes/aggregation_test.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/sqltypes/const.go
Move the files in `expression`  directory to the `sqltypes` folder.
=> *: move aggregation to sqltypes folder

src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/ast.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/parse_test.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/sql.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/sql.y
https://github.com/radondb/radon/issues/472
reference: `https://github.com/sougou/vitess/commit/be01cef69ab349e4766d8edf179a7300332b2f4b`
=> sqlparser: fix interval parser error #472

src/proxy/ddl.go, src/proxy/ddl_test.go
[summary]
Debug and find some error log is Confused:
meaning is related to privilege from log but actually it is not.
[test case]
proxy/ddl_test.go
100%
=> proxy: improve the err output and log about unsupported ddl #487

src/proxy/ddl.go, src/router/frm.go, src/router/frm_test.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/ast.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/sql.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/sql.y
[summary]
adjust partitionTableType to add more type partition
[test case]
router/frm_test.go
100%
=> *: adjust partition to add more type partition #491

src/config/config.go, src/config/config_test.go, src/config/mock.go
[summary]
add ListValue on the PartitionConfig to the partition list
[test case]
src/config/config_test.go
86.5%
=> config: add ListValue on the PartitionConfig for the partition list #491

src/router/partition.go, src/router/router.go, src/router/router_test.go
[summary]
add the interface about partition type
[test case]
src/router/router_test.go
100%
=> router: add the interface about partition type #491

src/proxy/ddl.go, src/proxy/version_test.go, src/router/compute.go, src/router/compute_test.go, src/router/frm.go, src/router/frm_test.go, src/router/list.go, src/router/list_test.go, src/router/mock.go, src/router/partition.go, src/router/router.go, src/router/router_test.go, src/router/types.go, src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/ddl_test.go
[summary]
router add partition list
[test case]
src/router/compute_test.go
src/router/frm_test.go
src/router/list_test.go
src/router/router_test.go
src/router/compute.go 100%
src/router/frm.go 79.1%
src/router/list.go 93.3%
src/router/router.go 93.3%
=> router: add partition list #491

src/planner/builder/builder_test.go, src/planner/builder/from.go, src/planner/builder/from_test.go, src/planner/builder/join_node.go, src/router/mock.go
[summary]
planner add partition list
[test case]
src/planner/builder/from_test.go
src/planner/builder/builder.go 96.1%
src/planner/builder/join_node.go 90.6%
=> planner: add partition list #491

src/ctl/v1/shard.go, src/ctl/v1/shard_test.go, src/planner/builder/builder_test.go, src/proxy/ddl.go, src/proxy/ddl_test.go, src/router/list.go
[summary]
proxy add partition list
ctl add partition list
[test case]
src/proxy/ddl_test.go
src/ctl/v1/shard_test.go
src/proxy/ddl.go 93.6%
src/ctl/v1/shard.go 88.3%
=> proxy,ctl: add partition list #491

src/proxy/show.go, src/proxy/show_test.go
[summary]
add partition list to show create table
[test case]
src/proxy/show_test.go
src/proxy/show.go 88.1%
=> proxy: add partition list to show create table #491

docs/radon_sql_support.md
[summary]
add partition list to docs
[test case]
N/A
N/A
=> docs: add partition list to radon_sql_support.md #491

src/planner/builder/expr.go, src/planner/builder/expr_test.go, src/planner/builder/project.go, src/planner/builder/project_test.go
#441 
[summary]
push expr into subquery need replace the cols based on the fields in subquery.
[test case]
src/planner/builder 97.6%
=> builder: add replaceCol and replaceSelect #441

src/planner/builder/builder.go, src/planner/builder/common.go, src/planner/builder/expr.go, src/planner/builder/from.go, src/planner/builder/from_test.go, src/planner/builder/join_node.go, src/planner/builder/merge_node.go, src/planner/builder/plan_node.go, src/router/router.go
[summary]
rename Variable name, Function name
fix comments
[test case]
N/A
N/A
=> planner: rename some names and fix comments #480

src/planner/builder/builder.go, src/planner/builder/expr.go, src/planner/builder/expr_test.go, src/planner/builder/plan_node.go
[summary]
replace the verbose variables with meaningful variables
[test case]
N/A
N/A
=> planner/builder: make the code easy to understand #480

src/ctl/v1/user.go, src/ctl/v1/user_test.go
#551 
[summary]
Get usrz add superpriv parameter.
[test case]
src/ctl/v1/user_test.go
src/ctl/v1/user.go 96.2%
=> ctl/v1: userz add superpriv parameter #551

docs/radon_sql_support.md
Add `radon reshard|detach|attach|attachlist` instructions.
=> docs: update radon_sql_support.md

docs/radon_sql_support.md
[summary]
add `SHOW FULL COLUMNS\TABLES`, update the index.
[test case]
N/A
N/A
=> docs: update radon_sql_support.md #533

docs/api.md
[summary]
Add migrate API description.
[test case]
N/A
N/A
=> docs: update api.md #558

docs/api.md, docs/radon_sql_support.md
[summary]
Add some information.
[test case]
N/A
N/A
=> docs: update api.md and radon_sql_support,md

docs/api.md, docs/radon_sql_support.md
[summary]
Add some information.
[test case]
N/A
N/A
=> docs: update api.md and radon_sql_support.md

.travis.yml, .travis/radon-test/mtr.sh, .travis/radon-test/r/ddl.result, .travis/radon-test/r/select.result, .travis/radon-test/t/ddl.test, .travis/radon-test/t/select.test
[summary]
ci: support intergration test
[test case]
N/A
N/A
=> ci: add integration test #594

intergration/radon-test/mtr.sh, intergration/radon-test/r/create.result, intergration/radon-test/t/create.test
[summary]
complete intergration on create test.
port from : https://github.com/mysql/mysql-server/blob/8.0/mysql-test/t/create.test
[test case]
N/A
N/A
=> intergration: complete create.test #613

src/backend/connection.go, src/backend/pool.go, src/backend/pool_test.go, src/proxy/show.go, src/xbase/stats/counters.go, src/xbase/stats/counters_test.go
[summary]
Remove the backslash and tabs.
[test case]
N/A
N/A
=> *: optimize the output of show status #630

docs/radon_sql_support.md
[summary]
complete details on create grammar.
[test case]
N/A
N/A
=> docs: complete create grammar #647

docs/api.md
[summary]
complete address segment description in api.md
[test case]
N/A
N/A
=> docs: complete address segment description #620

docs/sql_statements/radon_administration_statements.md
[summary]
add radon rebalance in the sql_statements/radon_administration_statements.md
[test case]
N/A
N/A
=> docs: add radon rebalance

docs/how_to_build_and_run_radon.md
[summary]
fix broken link on radon_sql_statements_manual
[test case]
N/A
N/A
=> docs:fix broken link on radon_sql_statements_manual #665

docs/api.md
[summary]
fix address segment description in api.md
[test case]
N/A
N/A
=> docs: fix address segment description #620

docs/sql_statements/data_definition_statements.md, docs/sql_statements/database_administration_statements.md
add `partition num`|`show index`|`show collation`|`show charset` illustration.
=> docs: update sql_statements

docs/how_to_import_and_export_data.md
https://github.com/xelabs/go-mydumper/blob/master/README.md
=> docs: update how_to_import_and_export_data.md
