radondb/radon

- src/proxy/query.go
- src/proxy/query_test.go
```
mysql> select * from (select * from tb1) as tb;
ERROR 1105 (HY000): unsupported: subqueries.in.select
```
> proxy: fix the unsupport subquery report err #154

- src/proxy/delete.go
- src/proxy/execute.go
- src/proxy/insert.go
- src/proxy/select.go
- src/proxy/update.go
statement, rename some functions to clear covered scope #77
the last change about ExecuteTwoPC is:
https://github.com/radondb/radon/commit/4b6377edd8c4dd87e991a1b0b5a82686d96617e4
> proxy: change ExecuteTwoPC to be original just handling the single

- src/planner/join_node.go
- src/planner/select_plan_test.go
```
mysql> explain select tb3.a,tb5.b from tb3 join tb5 on tb3.a+1=tb5.a;
+----------------------------------------------------------------------------------------------------------------------------+
| EXPLAIN …
```
> planner: merge join support non-column types equivalent

- src/planner/aggregate_plan_test.go
- src/planner/expr.go
- src/planner/expr_test.go
- src/planner/select_plan.go
If the group by fields contain shard key,  only need to push down the group by to backend. Neednot process on the radon.
Prerequisite:
1.The plannode is MergeNode.
2.Select list doesnot contain aggregate function.
> planner: group by contain shard key optimization

- src/planner/aggregate_plan_test.go
- src/planner/expr_test.go
- src/planner/merge_node.go
- src/planner/select_plan.go
- src/planner/select_plan_test.go
https://github.com/radondb/radon/pull/341
group by with shard key,  at the same time contain aggregate function, such as (a is shard key): 
```
select a,count(b) from tb3 group by a;
```
we neednot process group by and count on radon.
```
mysql> explain select a,count(b) from tb3 group by a;
+-------------------------------------------------------------------------------------+
| EXPLAIN …
```
> planner: group by with aggregate optimization

- src/planner/aggregate_plan_test.go
- src/planner/expr.go
- src/planner/expr_test.go
- src/planner/join_node.go
- src/planner/orderby_plan.go
- src/planner/orderby_plan_test.go
- src/planner/plan_node.go
- src/planner/select_plan_test.go
```
mysql> select a as b from t1 order by a;
+---+
| b |
+---+
| 1 |
| 2 |
| 3 |
| 4 |
| 5 |
+---+
5 rows in set (1.19 sec)
mysql> select a as b from t1 order by t1.a;
+---+
| b |
+---+
| 1 |
| 2 |
| 3 |
| 4 |
| 5 |
+---+
5 rows in set (1.06 sec)
mysql> select a as b from t1 order by t1.b;
ERROR 1105 (HY000): unsupported: orderby[t1.b].should.in.select.list
mysql> select a as b from t1 order by b;
+---+
| b |
+---+
| 1 |
| 2 |
| 3 |
| 4 |
| 5 |
+---+
5 rows in set (1.06 sec)
mysql> select a,b from t1 order by b;
+---+------+
| a | b    |
+---+------+
| 3 | a    |
| 1 | b    |
| 4 | b    |
| 2 | c    |
| 5 | d    |
+---+------+
5 rows in set (1.09 sec)
```
> planner: fix groupby and orderby return wrong results' bug #346

- .codecov.yml
[summary]
1. change the precision from 2 to 0 (xx%)
2. allowed to drop 1% and still result in a success commit status
[test case]
N/A
N/A
> codecov: enable the codecov threshold

- src/vendor/github.com/radondb/shift/cli/cli.go
- src/vendor/github.com/radondb/shift/shift/mock.go
- src/vendor/github.com/radondb/shift/shift/shift.go
- src/vendor/github.com/radondb/shift/shift/shift_test.go
[summary]
1. Now the use of shift.Close() API is not friendly to users, I`ll try to improve it.
2. The error info should be more clear. It makes users confused.
[test case]
shift_test.go
89.9%
> shift: improve the shift.Close() API and some error logs #479

- src/proxy/admin_reshard.go
- src/proxy/admin_reshard_test.go
- src/proxy/admin_shift.go
- src/proxy/admin_shift_test.go
- src/proxy/radon.go
- src/proxy/set.go
- src/proxy/show_test.go
- src/router/frm.go
- src/router/frm_test.go
- src/router/hash.go
[summary]
Syntax:
RADON RESHARD tbl_name TO new_tbl_name
You can use RADON RESHARD to shift data from one SINGLE table
to another PARTITION table, the cmd execute the shift cmd and
will return immediately, the shift will run in background on
other goroutine.
NOTICE: the SINGLE table with the primary key can be partitioned.
TODO: the shift progress bar will call other interface
[test case]
src/proxy/admin_reshard_test.go
src/proxy/admin_shift_test.go
src/router/frm_test.go
src/proxy/admin_reshard.go: 98.4%
src/proxy/admin_shift.go: 81.8%
src/router/frm.go: 100%
> proxy: add reshard handle #436

- docs/api.md
- src/ctl/v1/user.go
- src/ctl/v1/user_test.go
[summary]
Now when we create user, it has all privileges, so we should give host
and [select|insert|update|delete] options to limit the privilege.
[test case]
TestCtlV1CreateUserError
TestCtlV1CreateUserHostAndPriv
TestCtlV1AlterUser
TestCtlV1DropUser
ctl/v1/user.go (96.6%)
> ctl: add more details for privilege options #470

- src/proxy/query.go
- src/proxy/query_test.go
[summary]
fix panic:
runtime error: invalid memory address or nil pointer dereference
[test case]
src/proxy/query_test.go
100%
> proxy: fix the panic #495

- src/fakedb/fakedb.go
- src/proxy/auth.go
- src/proxy/auth_test.go
- src/proxy/spanner.go
- src/proxy/version.go
- src/proxy/version_test.go
- src/router/frm.go
- src/vendor/github.com/xelabs/go-mysqlstack/driver/mock.go
- src/vendor/github.com/xelabs/go-mysqlstack/driver/server.go
- src/vendor/github.com/xelabs/go-mysqlstack/proto/statement_test.go
[summary]
because some jdbc need the version of MySQL
add backend version to the serverversion
serverversion="$MySQL" + "-" + "$tag"
[test case]
src/proxy/version_test.go
src/proxy/version_test.go (92.7%)
> *: add backend version to the serverversion #495

- src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/ast.go
- src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/ast_test.go
[summary]
In order to swap expression out of the subqueries, we need the ability to replace an expression with another.
The purpose of CloneExpr is to create a new expression based on the provided expression, which is used in JoinNode.
[test case]
src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/ast_test.go
86.1%
> sqlparser: replace and clone expression #441

- src/executor/engine/join_engine_test.go
- src/executor/engine/merge_engine.go
- src/executor/engine/merge_engine_test.go
- src/planner/merge_node.go
- src/planner/select_plan_test.go
[summary]
getFields need use GenerateQuery if the selectexprs contain bindvars.
[test case]
src/executor/engine/join_engine_test.go
src/executor/engine/merge_engine_test.go
src/planner/select_plan_test.go
src/executor/engine/merge_engine.go 100%
src/planner/merge_plan.go 97.3%
> *: fix getFields report missing bindvar #501

- src/executor/engine/join_engine.go
- src/executor/engine/merge_join.go
- src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/sqltypes/arithmetic.go
- src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/sqltypes/arithmetic_test.go
[summary]
Using CastToBool instead of judging value directly will make the result more accurate.
[test case]
src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/sqltypes/arithmetic_test.go
94.2%
> *: support cast value to boolean #480

- src/proxy/ddl.go
- src/proxy/ddl_test.go
[summary]
when create table with no database selected, we return
"ERROR 1046 (3D000): No database selected".
[test case]
src/proxy/ddl_test.go
src/proxy/ddl_test.go 93.9%
> proxy: modify incorrect MySQL errcode #280

- src/planner/builder/common.go
- src/planner/builder/expr.go
- src/planner/builder/join_node.go
- src/planner/builder/project.go
[summary]
Add info into selectTuple, to record the cols|refertable|expr from selectexpr.
When pushselectexpr during process subquery, we need replace the cols with fields in subquery.
[test case]
N/A
N/A
> builder: refactor the selectTuple #441

- src/planner/builder/builder.go
- src/planner/builder/builder_test.go
- src/planner/builder/expr.go
- src/planner/builder/expr_test.go
- src/planner/select_plan_test.go
issue : #520
[summary]
Colname in having must be included in fields, need check in parseHaving.
[test case]
src/planner/select_plan_test.go
src/planner/builder 97.8%
> planner: rewrite parseHaving function #520

- src/executor/engine/join_engine_test.go
- src/executor/engine/merge_engine_test.go
- src/planner/builder/builder.go
- src/planner/builder/builder_test.go
- src/planner/builder/common.go
- src/planner/builder/expr.go
- src/planner/builder/expr_test.go
- src/planner/builder/from_test.go
- src/planner/builder/join_node.go
- src/planner/builder/merge_node.go
- src/planner/builder/plan_node.go
- src/planner/builder/project.go
- src/planner/select_plan_test.go
[summary]
By analyzing the filter to automatically choose appropriate join strategy, instead of use hint.
[test case]
src/executor/engine/join_engine_test.go
src/planner/builder/from_test.go
src/planner/select_plan_test.go
src/planner/builder 97.8%
> *: change join strategy choice logic #480

- src/executor/engine/merge_join.go
- src/planner/builder/builder_test.go
- src/planner/builder/expr.go
- src/planner/builder/join_node.go
- src/planner/builder/project.go
[summary]
fix the error output and improve the test coverage
[test case]
src/planner/builder/project.go 98.1%
> planner: fix the error output and improve the test coverage #525

- src/executor/engine/merge_join.go
- src/planner/builder/builder.go
- src/planner/builder/builder_test.go
- src/planner/builder/expr_test.go
- src/planner/builder/from.go
- src/planner/builder/join_node.go
- src/planner/builder/merge_node.go
- src/planner/builder/plan_node.go
- src/planner/builder/plan_node_test.go
- src/planner/builder/project.go
- src/planner/builder/project_test.go
- src/planner/builder/union_node.go
[summary]
Merge SelectNode to PlanNode. The functions in UnionNode will used in subquery patch.
[test case]
src/planner/builder 97.6%
In function `processPart`:
```
if len(part.OrderBy) > 0 && part.Limit == nil {	
part.OrderBy = []*sqlparser.Order{}	
}
```
is delete, because the code is an optional extra, and subquery will call the function.
Some functions in UnionNode are temporarily unreachable, it will used in subquery patch. I will rewrite the code in subquery patch. And the cove coverage is temporarily decline, will improve soon.
Some testcase were rewrited, the purpose is to improve the code coverage.
> builder: refactor PlanNode and SelectNode #480

- src/planner/builder/expr.go
- src/planner/builder/expr_test.go
- src/planner/delete_plan_test.go
- src/planner/update_plan_test.go
[summary]
GetDMLRouting support in expression.
[test case]
src/planner/delete_plan_test.go
src/planner/update_plan_test.go
src/planner/builder/expr.go 98.9%
> planner: GetDMLRouting support in expression #535

- src/backend/scatter.go
- src/backend/scatter_test.go
- src/ctl/v1/backend_test.go
- src/proxy/admin_attach_test.go
#546
[summary]
Check address when add backend, to avoid the `xid already exists` error.
[test case]
src/backend/scatter_test.go
src/ctl/v1/backend_test.go
src/proxy/admin_attach_test.go
src/backend/scatter.go 88.7%
> src: check address when add backend #546

- src/audit/audit.go
- src/audit/audit_easyjson.go
- src/audit/audit_test.go
- src/proxy/audit.go
- src/proxy/query.go
- src/proxy/query_test.go
[summary]
Add status parameter to record the status of results. If 0 sucess, else failed.
[test case]
src/audit/audit_test.go
src/audit/audit.go 86.8%
src/audit/audit_easyjson.go 98.2%
src/proxy/audit.go 100%
> src: audit add status parameter #548

- .travis.yml
- .travis/backend.json
- .travis/my3306.cnf
- .travis/my3307.cnf
- .travis/my3309.cnf
- src/vendor/github.com/radondb/shift/makefile
- src/vendor/github.com/radondb/shift/shift/shift.go
- src/vendor/github.com/radondb/shift/shift/shift_test.go
- src/vendor/github.com/radondb/shift/vendor/github.com/siddontang/go-mysql/canal/dump.go
- src/vendor/github.com/radondb/shift/vendor/github.com/siddontang/go-mysql/canal/handler.go
[summary]
Now we use wg.Add(1) / wg.Done() / wg.Wait() in different goroutines,
This way of use wg is not correct and will caused DATA RACE:
goroutine1--->wg.Add(1)
goroutine2--->wg.Done()
goroutine3--->wg.Wait()
The right way to use it will be, e.g.:
goroutine1--->wg.Add(1), wg.Wait()
goroutine2--->wg.Done()
[test case]
vendor/github.com/radondb/shift/shift/shift_test.go
vendor/github.com/radondb/shift/shift	coverage: 76.1% of statements
vendor/github.com/siddontang/go-mysql/canal	coverage: 59.0% of statements
> shift: fix the wrong way to use waitGroup in three goroutines #556

- src/ctl/router.go
- src/ctl/v1/shard.go
- src/ctl/v1/shard_test.go
[summary]
Used to migrate data from one backend to another.
Path:   v1/shard/migrate
Method: POST
[test case]
src/ctl/v1/shard_test.go
src/ctl/v1/shard.go 90.3%
```
mysql> explain select * from t1;
+---------------------------------------------------------------------+
| EXPLAIN                                                                                                                   
+---------------------------------------------------------------------+
| {
"RawQuery": " select * from t1",
"Project": "*",
"Partitions": [
{
"Query": "select * from zzq.t1",
"Backend": "backend1",
"Range": ""
}
]
} |
+---------------------------------------------------------------------+
1 row in set (0.00 sec)
```
migrate `t1` from `backend1` to `backend2`:
```
$ curl -i -H …
```
> ctl: add an api to migrate data from one backend to another #558

- src/vendor/github.com/radondb/shift/shift/delete.go
- src/vendor/github.com/radondb/shift/shift/shift.go
- src/vendor/github.com/radondb/shift/shift/shift_test.go
- src/vendor/github.com/radondb/shift/shift/update.go
[summary]
1. db or table name may include "-", like "a-b_db" or "a-b_tbl"
2. column name may be a keyword, like "char", "key"...
They should be quoted when send delete/update sql to backend.
[test case]
vendor/github.com/radondb/shift/shift_test
vendor/github.com/radondb/shift/shift   coverage: 76.1% of statements
> shift: fix bug for unquoted col or table #560

- .gitignore
- docs/api.md
- src/ctl/v1/radon.go
- src/ctl/v1/radon_test.go
- src/proxy/proxy.go
- src/proxy/proxy_test.go
[summary]
Support modify blocks-readonly by /v1/radon/config api.
[test case]
src/ctl/v1/radon_test.go
src/proxy/proxy_test.go
src/ctl/v1/radon.go 92.4%
src/proxy/proxy.go 85.5%
```
$ curl -i -H 'Content-Type: application/json' -X PUT -d '{"blocks-readonly":64}' http://127.0.0.1:8080/v1/radon/config
HTTP/1.1 200 OK
Date: Fri, 17 Jan 2020 08:08:23 GMT
Content-Length: 0
```
> *: config api support modify blocks-readonly #573

- src/ctl/v1/shard.go
- src/ctl/v1/shard_test.go
- src/proxy/execute_test.go
- src/proxy/query.go
[summary]
Part of radon admin operations and migrate api need to add restrictions when radon in readonly.
[test case]
src/ctl/v1/shard_test.go
src/proxy/execute_test.go
src/ctl/v1/shard.go 90.3%
src/proxy/query.go 88.2%
> *: forbid some operations when radon readonly #578

- src/proxy/admin_cleanup_test.go
- src/proxy/query.go
[summary]
Part of radon admin operations api need to add restrictions when radon in readonly.
[test case]
src/proxy/admin_cleanup_test.go
src/proxy/query.go 88.2%
> proxy: forbid radon cleanup admin when readonly #578

- src/config/config.go
[summary]
Add double quotes for xa-check-retrys.
[test case]
N/A
N/A
> config: fix missing double quotes #603

- src/vendor/github.com/xelabs/go-mysqlstack/driver/client.go
[summary]
Fix the panic 'close of closed channel'.
[test case]
N/A
N/A
> go-mysqlstack: fix the panic close of closed channel #614

- src/proxy/query.go
- src/proxy/query_test.go
[summary]
Add hint for streaming fetch.
select /*+ streaming */
[test case]
src/proxy/query_test.go
src/proxy/query.go 88.6%
> proxy: add hint for streaming fetch #619

- src/backend/mock.go
- src/backend/pool.go
- src/backend/pool_test.go
- src/backend/queryz_test.go
- src/backend/scatter.go
- src/backend/scatter_test.go
- src/backend/txn.go
- src/backend/txn_test.go
- src/backend/txnmgr.go
- src/backend/txnmgr_test.go
- src/config/config.go
- src/ctl/v1/backend.go
- src/ctl/v1/backend_test.go
- src/ctl/v1/radon.go
- src/ctl/v1/radon_test.go
- src/proxy/execute.go
- src/proxy/multistmt_txn.go
- src/proxy/proxy.go
- src/proxy/proxy_test.go
- src/proxy/show.go
[summary]
1.config
Add 'replica-address' to backend config, identify read-only backends vip.
Add 'loadbalance' to proxy config, 0 -- disable balance, 1 -- enable balance to replica.
2.When the statement is read and not in a multi-statement transaction, the sql will sent to the 'replica-address' for execution.
[test case]
src/backend/pool_test.go
src/backend/queryz_test.go
src/backend/txn_test.go
src/backend/txnmgr_test.go
src/proxy/proxy_test.go
src/backend/mock.go 98.8%
src/backend/pool.go 90.9%
src/backend/txn.go 89.1%
src/backend/txnmgr.go 88.5%
src/proxy/proxy.go 86.0%
> *: support read-write separation #624

- docs/api.md
- docs/radon_sql_support.md
- src/backend/txn.go
- src/backend/txn_test.go
- src/proxy/execute.go
- src/proxy/execute_test.go
- src/proxy/multistmt_txn.go
[summary]
The query with '/\*+loadbalance=0\*/' will be forced to execute on normal, which means loadbalance'll be disabled.
[test case]
src/backend/txn_test.go
src/proxy/execute_test.go
src/backend/txn.go 88.8%
src/proxy/execute.go 87.6%
> *: add hint for read-write separation #624

- src/proxy/explain.go
- src/proxy/explain_test.go
In `Radon`:
```
mysql> explain select * from test.t;
+--------------------------------------------------------+
| EXPLAIN                                                |
+--------------------------------------------------------+
| unsupported: cannot.explain.the.query: select * from t |
+--------------------------------------------------------+
1 row in set (0.00 sec)
```
In `MySQL`:
```
mysql> explain select * from test.t;
ERROR 1146 (42S02): Table 'test.t' doesn't exist
```
[summary]
We need more detail about the explain error output, just like MySQL.
[test case]
src/proxy/explain_test.go
src/proxy/explain.go 91.7%
> proxy: more detailed explain error output #644

- src/backend/txn.go
- src/backend/xa.go
- src/executor/engine/join_engine.go
- src/executor/engine/union_engine.go
- src/vendor/github.com/golang/sync/errgroup/errgroup.go
- src/vendor/github.com/golang/sync/errgroup/errgroup_example_md5all_test.go
- src/vendor/github.com/golang/sync/errgroup/errgroup_test.go
https://github.com/radondb/radon/issues/480#issuecomment-636710899
[summary]
Package errgroup provides synchronization, error propagation, and Context cancelation for groups of goroutines working on subtasks of a common task.
We can use the errgroup to handle error under concurrency.
[test case]
N/A
src/backend/txn.go 89.8%
src/backend/xa.go 91.1%
src/executor/engine/join_engine.go 95.7%
src/executor/engine/union_engine.go 93.9%
> *: use errgroup to handle error under concurrency #480

- src/backend/txn.go
- src/backend/xa_test.go
- src/proxy/execute.go
- src/proxy/execute_test.go
[summary]
RollbackPhaseOne used to rollback when the SQL return error at the phase one.
won't do `XA PREPARE` which will write log to binlog, especially when large Transactions happen.
[test case]
src/backend/xa_test.go
src/backend/txn.go 89.8%
src/proxy/execute.go 87.8%
> *: add RollbackPhaseOne at the phase one.

- README.md
- conf/conf.json.sample
- conf/radon.default.json
- docs/api.md
- src/config/config.go
- src/proxy/iptable.go
- src/proxy/iptable_test.go
[summary]
The config allowsip supports address segments regexp defined by users.
address supported may be like: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
ip regexp is "*", that means allows all ip connect to radon
[test case]
iptable_test.go
src/proxy/iptable.go 97.8%
> proxy: support allow ip regexp in config file #620

- intergration/radon-test/r/ddl.result
- intergration/radon-test/r/select.result
- intergration/radon-test/t/ddl.test
- intergration/radon-test/t/select.test
- src/planner/builder/aggregate_plan.go
- src/planner/builder/common.go
- src/planner/builder/expr.go
- src/planner/builder/expr_test.go
- src/planner/builder/from.go
- src/planner/builder/from_test.go
- src/planner/builder/join_node.go
- src/planner/builder/merge_node.go
- src/planner/builder/orderby_plan_test.go
- src/planner/builder/project.go
- src/planner/builder/project_test.go
- src/planner/common.go
- src/planner/ddl_plan.go
- src/planner/ddl_plan_test.go
- src/planner/insert_plan.go
- src/planner/insert_plan_test.go
- src/proxy/ddl.go
- src/proxy/ddl_test.go
[summary]
Set the column and column aliases not case-sensitive.
[test case]
src/planner/builder/from_test.go
src/planner/builder/orderby_plan_test.go
src/planner/builder/project_test.go
src/planner/ddl_plan_test.go
src/planner/insert_plan_test.go
src/proxy/ddl_test.go
src/planner/builder/common.go 100%
src/planner/builder/expr.go 99.0%
src/planner/builder/from.go 99.3%
src/planner/builder/merge_node.go 97.3%
src/planner/builder/project.go 98.2%
src/planner/common.go 100%
src/planner/ddl_plan.go 93.8%
src/planner/insert_plan.go 96.0%
src/proxy/ddl.go 94.7%
> *: fix the bug that columns are case sensitive #673

- src/backend/scatter.go
- src/monitor/monitor.go
- src/monitor/monitor_test.go
[summary]
The slave node of Radon will synchronize metadata from the master node. At this time, backend.json will be reloaded, causing backendnum to be counted repeatedly.
Set 0 before reload the backend config.
[test case]
src/monitor/monitor_test.go
src/monitor/monitor.go 96.3%
src/backend/scatter.go 88.7%
> *: fix the backendnum statistics error #698

- src/planner/builder/aggregate_plan.go
- src/planner/builder/limit_plan.go
- src/planner/builder/orderby_plan.go
- src/planner/ddl_plan.go
- src/planner/delete_plan.go
- src/planner/insert_plan.go
- src/planner/others_plan.go
- src/planner/select_plan.go
- src/planner/select_plan_test.go
- src/planner/union_plan.go
- src/planner/update_plan.go
- src/proxy/explain_test.go
- src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/common/unsafe.go
- src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/common/unsafe_test.go
[summary]
Use an Encoder by calling SetEscapeHTML(false) to avoid the mistake.
[test case]
src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/common/unsafe_test.go
src/vendor/github.com/xelabs/go-mysqlstack/sqlparser/depends/common/unsafe.go 94.4%
> *: fix bug explain has problem of escaping characters #706
